/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import GUI.TableModels.BasicInfoModel;
import GUI.TableModels.AbilityModel;
import AssetDB.DBManager;
import GUI.TableModels.ArrayOfRowsModel;
import GUI.TableModels.SkillsModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Shazzama.Pajama
 */
public class DnDDatabase extends javax.swing.JFrame {
    private DBManager dbManager;
    
    
    /**
     * Creates new form DnDDatabase
     */
    public DnDDatabase() {
        initComponents();
        dbManager = new DBManager();
        
        //initialize table
        try {
            ArrayList<ArrayList<Object>> table = dbManager.getBasicInfoRows(dbManager.getAllCharacters());
            BasicInfoModel newmodel = new BasicInfoModel(table);
            jTableCharacters.setModel(newmodel);
            
        } catch (SQLException ex) {
            Logger.getLogger(DnDDatabase.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCharacters = new javax.swing.JTable();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldRace = new javax.swing.JTextField();
        jTextFieldType = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jLabelRace = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jButtonSearchCharacter = new javax.swing.JButton();
        jLabelAbility = new javax.swing.JLabel();
        jComboBoxAb = new javax.swing.JComboBox();
        jButtonSearchAb = new javax.swing.JButton();
        jTextFieldAb = new javax.swing.JTextField();
        jLabelAbVal = new javax.swing.JLabel();
        jLabelBasic = new javax.swing.JLabel();
        jComboBoxBasic = new javax.swing.JComboBox();
        jTextFieldStatVal = new javax.swing.JTextField();
        jLabelStatVal = new javax.swing.JLabel();
        jButtonSearchBasic = new javax.swing.JButton();
        jLabelSkill = new javax.swing.JLabel();
        jComboBoxSkills = new javax.swing.JComboBox();
        jTextFieldSkillVal = new javax.swing.JTextField();
        jButtonSkillSearch = new javax.swing.JButton();
        jLabelSkillVal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        jButtonViewAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableCharacters.setAutoCreateRowSorter(true);
        jTableCharacters.setModel(new BasicInfoModel());
        jTableCharacters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCharactersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCharacters);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setText("D&D Asset Database");

        jTextFieldType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTypeActionPerformed(evt);
            }
        });

        jLabelName.setText("Name:");

        jLabelRace.setText("Race");

        jLabelType.setText("Type");

        jButtonSearchCharacter.setText("Search");
        jButtonSearchCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCharacterActionPerformed(evt);
            }
        });

        jLabelAbility.setText("Ability:");

        jComboBoxAb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL", "Strength", "Constitution", "Dexterity", "Intelligence", "Wisdom", "Charisma", " " }));

        jButtonSearchAb.setText("Search");
        jButtonSearchAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchAbActionPerformed(evt);
            }
        });

        jLabelAbVal.setText("Value:");

        jLabelBasic.setText("Basic Stat:");

        jComboBoxBasic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "Race", "Type", "Class", "Alignment", "Level", "HitPoints", "ArmorClass", "AtkBonus" }));

        jLabelStatVal.setText("Value:");

        jButtonSearchBasic.setText("Search");
        jButtonSearchBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchBasicActionPerformed(evt);
            }
        });

        jLabelSkill.setText("Skill:");

        jComboBoxSkills.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acrobatics", "Arcana", "Athletics", "Bluff", "Diplomacy", "Dungeoneering", "Endurance", "Heal", "History", "Insight", "Intimidate", "Nature", "Perception", "Religion", "Stealth", "Streetwise", "Thievery" }));

        jButtonSkillSearch.setText("Search");
        jButtonSkillSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSkillSearchActionPerformed(evt);
            }
        });

        jLabelSkillVal.setText("Value:");

        jButton2.setText("ViewCharacter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add Character");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonViewAll.setText("View All");
        jButtonViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addGap(341, 341, 341))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelName)
                                        .addGap(46, 46, 46))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelType)
                                        .addGap(53, 53, 53)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldType, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(jTextFieldRace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(NameField, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jLabelRace)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jButtonSearchCharacter)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jButtonSearchAb)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelBasic)
                                    .addComponent(jLabelStatVal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonSearchBasic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxBasic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldStatVal))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelAbility)
                                    .addComponent(jLabelAbVal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxAb, 0, 125, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAb))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSkill)
                                    .addComponent(jLabelSkillVal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSkillVal)
                                    .addComponent(jComboBoxSkills, 0, 125, Short.MAX_VALUE))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonSkillSearch)
                                .addGap(78, 78, 78))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 49, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRace))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelType)
                            .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jButtonSearchCharacter))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelAbility, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxAb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelSkill))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxBasic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelBasic)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldAb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelAbVal))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldStatVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelStatVal)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSearchBasic)
                            .addComponent(jButtonSearchAb)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxSkills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSkillVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSkillVal))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSkillSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButtonViewAll))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTypeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new CharacterSheet(this.dbManager).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonSkillSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSkillSearchActionPerformed
        String Skill = (String)jComboBoxSkills.getSelectedItem();
        SkillsModel newmodel;
        ResultSet data;
        ArrayList<ArrayList<Object>> table;
        
        if (jTextFieldSkillVal.getText().isEmpty()){
            try{
                data = dbManager.getOneSkillAll(Skill);
                table = dbManager.getSkillRows(Skill, data);
                
                newmodel = new SkillsModel(Skill, table);
                jTableCharacters.setModel(newmodel);
            }catch(SQLException ex){
            
            }            
        }else{
             try{
                data = dbManager.SkillQuery(Skill, jTextFieldSkillVal.getText());
                table = dbManager.getSkillRows(Skill, data);
                
                newmodel = new SkillsModel(Skill, table);
                jTableCharacters.setModel(newmodel);
            }catch(SQLException ex){
            
            }            
        }

        
        
    }//GEN-LAST:event_jButtonSkillSearchActionPerformed

    private void jButtonSearchAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchAbActionPerformed
        String Ability = (String)jComboBoxAb.getSelectedItem();
        String Value = jTextFieldAb.getText().trim();
        
        if (Ability.equals("ALL") == false){
            try{
                ResultSet tabledata = dbManager.AbilityQuery(Ability, Value);
                ArrayList<ArrayList<Object>> table = dbManager.getAbilityRows(tabledata);
                AbilityModel newmodel = new AbilityModel(table);
                jTableCharacters.setModel(newmodel);
            }catch(SQLException ex){
                ex.getMessage();
            }
        }else{
            try{
                ResultSet tabledata = dbManager.getAllAbilitySets();
                ArrayList<ArrayList<Object>> table = dbManager.getAbilityRows(tabledata);
                AbilityModel newmodel = new AbilityModel(table);
                jTableCharacters.setModel(newmodel);
            }catch(SQLException ex){
                ex.getMessage();
            }            
        }
        
        
    }//GEN-LAST:event_jButtonSearchAbActionPerformed

    private void jButtonSearchCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCharacterActionPerformed
        BasicInfoModel newmodel = new BasicInfoModel();
        
        String Name = NameField.getText().trim();
        String Race = jTextFieldRace.getText().trim();
        String Type = jTextFieldType.getText().trim();
        
        try {
            ResultSet character = dbManager.CharacterQuery(Name, Race, Type);
            ArrayList<ArrayList<Object>> rowset = dbManager.getBasicInfoRows(character);
            newmodel.setTable(rowset);
            jTableCharacters.setModel(newmodel);
            System.out.println("Action completed");
            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            System.out.println(ex.getSQLState());
        }
        
        jTableCharacters.setModel(newmodel);
        
        
        
    }//GEN-LAST:event_jButtonSearchCharacterActionPerformed

    private void jButtonSearchBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchBasicActionPerformed
        String Stat = (String)jComboBoxBasic.getSelectedItem();
        String Val  = jTextFieldStatVal.getText().trim();
        ArrayList<ArrayList<Object>> table = new ArrayList<>();
        
        try{
            ResultSet Rows = dbManager.QueryBasicStat(Stat, Val);
            table = dbManager.getBasicInfoRows(Rows);
            BasicInfoModel newmodel = new BasicInfoModel(table);
            jTableCharacters.setModel(newmodel);
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        
        
        
        
    }//GEN-LAST:event_jButtonSearchBasicActionPerformed

    private void jButtonViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllActionPerformed
        ArrayList<ArrayList<Object>> table;
        try {
            table = dbManager.getBasicInfoRows(dbManager.getAllCharacters());
            BasicInfoModel newmodel = new BasicInfoModel(table);
            jTableCharacters.setModel(newmodel);
        } catch (SQLException ex) {
            Logger.getLogger(DnDDatabase.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jButtonViewAllActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int rowindex = jTableCharacters.getSelectedRow();
        if(rowindex >= 0){
            ArrayOfRowsModel model = (ArrayOfRowsModel)jTableCharacters.getModel();
            ArrayList<Object> row = model.getRow(rowindex);
            String Name = (String)row.get(0);
            String Race = (String)row.get(1);
            String Type = (String)row.get(2);
            
            try {
                ArrayList<Object> BasicInfo = dbManager.getCharacterBasicInfo(Name, Race, Type);
                ArrayList<Integer> AbilityInfo = dbManager.getCharacterAbilities(Name, Race, Type);
                ArrayList<Integer> SkillInfo = dbManager.getCharacterSkills(Name, Race, Type);
                ArrayList<Integer> BasicScoreInfo = dbManager.getCharacterBasicScores(Name, Race, Type);
                
                String Desc = dbManager.getCharacterDescription(Name, Race, Type);
                String Extra = dbManager.getCharacterExtras(Name, Race, Type);
                
                new CharacterSheet(BasicInfo,BasicScoreInfo, AbilityInfo, SkillInfo, Desc, Extra, this.dbManager).setVisible(true);
                
                
            } catch (SQLException ex) {
                Logger.getLogger(DnDDatabase.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTableCharactersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCharactersMouseClicked
        if(evt.getClickCount() == 2){
            int rowindex = jTableCharacters.getSelectedRow();
            if(rowindex >= 0){
                ArrayOfRowsModel model = (ArrayOfRowsModel)jTableCharacters.getModel();
                ArrayList<Object> row = model.getRow(rowindex);
                String Name = (String)row.get(0);
                String Race = (String)row.get(1);
                String Type = (String)row.get(2);
            
                try {
                    ArrayList<Object> BasicInfo = dbManager.getCharacterBasicInfo(Name, Race, Type);
                    ArrayList<Integer> AbilityInfo = dbManager.getCharacterAbilities(Name, Race, Type);
                    ArrayList<Integer> SkillInfo = dbManager.getCharacterSkills(Name, Race, Type);
                    ArrayList<Integer> BasicScores = dbManager.getCharacterBasicScores(Name, Race, Type);
                    String Desc = dbManager.getCharacterDescription(Name, Race, Type);
                    String Extra = dbManager.getCharacterExtras(Name, Race, Type);
                
                
                new CharacterSheet(BasicInfo, BasicScores, AbilityInfo, SkillInfo, Desc, Extra, this.dbManager).setVisible(true);
                
                
                } catch (SQLException ex) {
                    Logger.getLogger(DnDDatabase.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jTableCharactersMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonSearchAb;
    private javax.swing.JButton jButtonSearchBasic;
    private javax.swing.JButton jButtonSearchCharacter;
    private javax.swing.JButton jButtonSkillSearch;
    private javax.swing.JButton jButtonViewAll;
    private javax.swing.JComboBox jComboBoxAb;
    private javax.swing.JComboBox jComboBoxBasic;
    private javax.swing.JComboBox jComboBoxSkills;
    private javax.swing.JLabel jLabelAbVal;
    private javax.swing.JLabel jLabelAbility;
    private javax.swing.JLabel jLabelBasic;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRace;
    private javax.swing.JLabel jLabelSkill;
    private javax.swing.JLabel jLabelSkillVal;
    private javax.swing.JLabel jLabelStatVal;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCharacters;
    private javax.swing.JTextField jTextFieldAb;
    private javax.swing.JTextField jTextFieldRace;
    private javax.swing.JTextField jTextFieldSkillVal;
    private javax.swing.JTextField jTextFieldStatVal;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
}
