/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import GUI.TableModels.BasicInfoModel;
import GUI.TableModels.AbilityModel;
import AssetDB.DBManager;
import GUI.TableModels.SkillsModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Shazzama.Pajama
 */
public class DnDDatabase extends javax.swing.JFrame {
    private DBManager dbManager;
    
    
    /**
     * Creates new form DnDDatabase
     */
    public DnDDatabase() {
        initComponents();
        dbManager = new DBManager();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCharacters = new javax.swing.JTable();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldRace = new javax.swing.JTextField();
        jTextFieldType = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jLabelRace = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jButtonSearchCharacter = new javax.swing.JButton();
        jLabelAbility = new javax.swing.JLabel();
        jComboBoxAb = new javax.swing.JComboBox();
        jButtonSearchAb = new javax.swing.JButton();
        jTextFieldAb = new javax.swing.JTextField();
        jLabelAbVal = new javax.swing.JLabel();
        jLabelBasic = new javax.swing.JLabel();
        jComboBoxBasic = new javax.swing.JComboBox();
        jTextFieldStatVal = new javax.swing.JTextField();
        jLabelStatVal = new javax.swing.JLabel();
        jButtonSearchBasic = new javax.swing.JButton();
        jLabelSkill = new javax.swing.JLabel();
        jComboBoxSkills = new javax.swing.JComboBox();
        jTextFieldSkillVal = new javax.swing.JTextField();
        jButtonSkillSearch = new javax.swing.JButton();
        jLabelSkillVal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableCharacters.setModel(new BasicInfoModel());
        jScrollPane2.setViewportView(jTableCharacters);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setText("D&D Asset Database");

        jTextFieldType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTypeActionPerformed(evt);
            }
        });

        jLabelName.setText("Name:");

        jLabelRace.setText("Race");

        jLabelType.setText("Type");

        jButtonSearchCharacter.setText("Search");
        jButtonSearchCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCharacterActionPerformed(evt);
            }
        });

        jLabelAbility.setText("Ability:");

        jComboBoxAb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "STR", "CON", "DEX", "INT", "WIS", "CHA" }));

        jButtonSearchAb.setText("Search");
        jButtonSearchAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchAbActionPerformed(evt);
            }
        });

        jLabelAbVal.setText("Value:");

        jLabelBasic.setText("Basic Stat:");

        jComboBoxBasic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "Race", "Type", "Class", "Alignment", "Level", "HP", "AC", "AtkBonus" }));

        jLabelStatVal.setText("Value:");

        jButtonSearchBasic.setText("Search");
        jButtonSearchBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchBasicActionPerformed(evt);
            }
        });

        jLabelSkill.setText("Skill:");

        jComboBoxSkills.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acrobatics", "Arcana", "Athletics", "Bluff", "Diplomacy", "Dungeoneering", "Endurance", "Heal", "History", "Insight", "Intimidate", "Nature", "Perception", "Religion", "Stealth", "Streetwise", "Thievery" }));

        jButtonSkillSearch.setText("Search");
        jButtonSkillSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSkillSearchActionPerformed(evt);
            }
        });

        jLabelSkillVal.setText("Value:");

        jButton2.setText("ViewCharacter");

        jButton3.setText("Add Character");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addGap(341, 341, 341))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelName)
                                        .addGap(46, 46, 46))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelType)
                                        .addGap(53, 53, 53)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldType, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldRace, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addComponent(jTextFieldName))))
                            .addComponent(jLabelRace)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jButtonSearchCharacter)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jButtonSearchAb)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelBasic)
                                    .addComponent(jLabelStatVal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonSearchBasic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxBasic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldStatVal))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelAbility)
                                    .addComponent(jLabelAbVal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxAb, 0, 125, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAb))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSkill)
                                    .addComponent(jLabelSkillVal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSkillVal)
                                    .addComponent(jComboBoxSkills, 0, 125, Short.MAX_VALUE))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonSkillSearch)
                                .addGap(78, 78, 78))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 49, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRace))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelType)
                            .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jButtonSearchCharacter))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelAbility, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxAb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelSkill))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxBasic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelBasic)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldAb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelAbVal))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldStatVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelStatVal)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSearchBasic)
                            .addComponent(jButtonSearchAb)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxSkills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSkillVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSkillVal))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSkillSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTypeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new CharacterSheet().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonSkillSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSkillSearchActionPerformed
        String Skill = (String)jComboBoxSkills.getSelectedItem();
        SkillsModel newmodel = new SkillsModel(Skill);
        
        jTableCharacters.setModel(newmodel);
    }//GEN-LAST:event_jButtonSkillSearchActionPerformed

    private void jButtonSearchAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchAbActionPerformed
        AbilityModel newmodel = new AbilityModel();
        
        jTableCharacters.setModel(newmodel);
    }//GEN-LAST:event_jButtonSearchAbActionPerformed

    private void jButtonSearchCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCharacterActionPerformed
        BasicInfoModel newmodel = new BasicInfoModel();
        
        jTableCharacters.setModel(newmodel);
    }//GEN-LAST:event_jButtonSearchCharacterActionPerformed

    private void jButtonSearchBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchBasicActionPerformed
        String Stat = (String)jComboBoxBasic.getSelectedItem();
        String Val  = jTextFieldStatVal.getText().trim();
        BasicInfoModel newmodel = new BasicInfoModel();
        
        try {
            ResultSet data = dbManager.QueryBasicStat(Stat, Val);
            
            while(data.next()){
                String Name = data.getString("Name");
                String Race = data.getString("Race");
                String Type = data.getString("Type");
                String Class = data.getString("Class");
                String Alignment = data.getString("Alignment");
                Integer HP = data.getInt("HitPoints");
                Integer AC = data.getInt("ArmorClass");
                Integer AtkBonus = data.getInt("AtkBonus");
                
                newmodel.addRow(Name, Race, Type, Class, Alignment, AC, HP, AC, AtkBonus);
            }
            jTableCharacters.setModel(newmodel);
        } catch (SQLException ex) {
            Logger.getLogger(DnDDatabase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSearchBasicActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonSearchAb;
    private javax.swing.JButton jButtonSearchBasic;
    private javax.swing.JButton jButtonSearchCharacter;
    private javax.swing.JButton jButtonSkillSearch;
    private javax.swing.JComboBox jComboBoxAb;
    private javax.swing.JComboBox jComboBoxBasic;
    private javax.swing.JComboBox jComboBoxSkills;
    private javax.swing.JLabel jLabelAbVal;
    private javax.swing.JLabel jLabelAbility;
    private javax.swing.JLabel jLabelBasic;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRace;
    private javax.swing.JLabel jLabelSkill;
    private javax.swing.JLabel jLabelSkillVal;
    private javax.swing.JLabel jLabelStatVal;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCharacters;
    private javax.swing.JTextField jTextFieldAb;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldRace;
    private javax.swing.JTextField jTextFieldSkillVal;
    private javax.swing.JTextField jTextFieldStatVal;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
}
